# TODO: update this from inside the build to use branch current version
version: '{build}'

#cache:
#- 'C:\Python38\'
#- 'C:\Python38-x64'
build_script: echo "Default to Script mode"

platform:
  - arm64
  - x86
  - x64

environment:
  libyaml_repo_url: https://github.com/yaml/libyaml.git
  libyaml_refspec: 0.2.2
  PYYAML_TEST_GROUP: all


  matrix:
    - PYTHON_VER: Python27
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python27-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PYTHON_VER: Python39
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - TOXENV: py27
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - TOXENV: py39
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    except:
      - platform: x64
  install: pip install cython tox
  build_script:
    - echo "Ubuntu build script $PYTHON_VER" && cat /etc/lsb-release && uname -ar
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    except:
      - platform: arm64
  build_script:
    - echo "Windows %APPVEYOR_BUILD_WORKER_IMAGE% %PYTHON_VER% build script"
      #build_script:
      #- ps: packaging\build\appveyor.ps1

#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
